apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation Component3
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1.0.2

      - name: Running Snyk SCA scan
        uses: cloudbees-io/snyk-sca-scan-dependency@v1
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: "LANGUAGE_JAVA"
          
      - name: Running Snyk SAST Scan
        uses: cloudbees-io/snyk-sast-scan-code@v1
        with:
          orgname: ${{ vars.SNYK_SAAS_ORG_NAME }}
          token: ${{ secrets.SNYK_SAAS_TOKEN }}
          language: "LANGUAGE_JAVA"
          
      - name: Maven Build
        uses: docker://maven:3.8.7-openjdk-18-slim
        run: |
          mvn clean install
          ls -lrt target/
          
      - name: ConfigureAWSCredentials
        uses: cloudbees-io/configure-aws-credentials@v0.0.4
        with:
          aws-access-key-id: ${{ secrets.RIQ_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RIQ_SECRET_KEY }}
          aws-region: us-west-2
      - name: DockerBuild
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component3:${{ cloudbees.scm.sha }}
          
      # - name: Running container scan using Trivy
      #   uses: cloudbees-io/trivy-scan-container@v1
      #   with:
      #     image-location: 641518622681.dkr.ecr.us-west-2.amazonaws.com/demo_component3
      #     image-tag: ${{ cloudbees.scm.sha }}

      - name: Trigger Spinnaker job using Cloudbees Spinnaker Action
        uses: cloudbees-io/spinnaker-run-pipeline@v1.0.0
        kind: deploy
        with:
          url: http://ec2-35-88-126-158.us-west-2.compute.amazonaws.com:8084
          token: ${{ secrets.SPINNAKER_TOKEN }}
          app-name: application001
          pipeline-name: pipeline002
